spring:
  datasource:
    url: jdbc:h2:mem:georentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: adviser
    password: arbitrary

  mail:
    host: smtp.gmail.com
    port: 587
    username: xxxxxxxxx@gmail.com
    password: xxxxxxx
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com