spring:
  profiles:
    #    active: dev
    active: test
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:georentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: adviser
    password: arbitrary