spring:
  datasource:
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    url: jdbc-secretsmanager:postgresql://aaa-instance.cekerrljrgxg.eu-west-1.rds.amazonaws.com:5432/adviserdb
    username: dev/aid-adviser/postgres

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        search:
          default:
            directory_provider: filesystem
            indexBase: /var/adviser/indexes/
          reindex: false