spring:
  datasource:
    url: jdbc:mysql://localhost:3306/avtoaid?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    platform: mysql
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: xxxxxxxxx@gmail.com
    password: xxxxxxx
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
      connectiontimeout: 5000
      timeout: 3000
      writetimeout: 5000

server:
  port: 8080
  servlet:
    context-path: /api

email:
  service: default
app:
  jwt:
    secretKey: super-secret-test-key
    expirationMillis: 3600000