spring:
  datasource:
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    url: jdbc-secretsmanager:postgresql://ec2-34-244-44-0.eu-west-1.compute.amazonaws.com/adviserdb
    username: dev/aid-adviser/postgres