create sequence hibernate_sequence start with 1 increment by 1;

create table adviser_usr (
    id bigint generated by default as identity,
    activation_code varchar(255),
    active boolean not null,
    email varchar(255) not null,
    password varchar(255) not null,
    role varchar(255) not null,
    primary key (id)
);

create table business (
    id bigint generated by default as identity,
    phone varchar(255),
    url varchar(255),
    address varchar(255),
    latitude serial not null,
    longitude serial not null,
    name varchar(255) not null,
    business_user_user_details_id bigint,
    primary key (id)
);

create table business_has_service (
    business_id bigint not null,
    service_for_businesses_id bigint not null,
    primary key (business_id, service_for_businesses_id)
);

create table business_type (
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table business_usr (
    user_details_id bigint not null,
    primary key (user_details_id)
);

create table car_brand (
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table car_model (
    id bigint generated by default as identity,
    name varchar(255),
    car_brand_id bigint,
    type_car_id bigint,
    primary key (id)
);

create table history_point (
    id bigint not null,
    search_date timestamp not null,
    user_id bigint not null,
    primary key (id)
);

create table image (
    id bigint generated by default as identity,
    key_file_name varchar(255) not null,
    original_file_name varchar(255),
    user_car_id bigint,
    business_id bigint,
    primary key (id)
);

create table point_with_business (
    history_point_id bigint not null,
    business_id bigint not null
);

create table service (
    id bigint generated by default as identity,
    name varchar(255) not null,
    service_type_id bigint,
    primary key (id)
);

create table service_type (
    id bigint generated by default as identity,
    name varchar(255) not null,
    business_type_id bigint,
    primary key (id)
);

create table simple_usr (
    first_name varchar(255),
    last_name varchar(255),
    phone varchar(255),
    user_details_id bigint not null,
    primary key (user_details_id)
);

create table type_car (
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table user_car (
    id bigint generated by default as identity,
    description varchar(255),
    individual_car_naming varchar(255),
    release_year integer,
    car_model_id bigint,
    simple_user_user_details_id bigint,
    primary key (id)
);

create table work_time (
    id bigint generated by default as identity,
    day integer,
    from_time time,
    to_time time,
    business_id bigint,
    primary key (id)
);

alter table adviser_usr add constraint UK_adviser_usr__email unique (email);
alter table business_type add constraint UK_business_type__name unique (name);
alter table service add constraint UK_service__name unique (name);
alter table service_type add constraint UK_service_type__name unique (name);

alter table business
    add constraint FK_business__business_usr
        foreign key (business_user_user_details_id) references business_usr;

alter table business_has_service
    add constraint FK_business_has_service__service
        foreign key (service_for_businesses_id) references service;

alter table business_has_service
    add constraint FK_business_has_service__business
        foreign key (business_id) references business;

alter table business_usr
    add constraint FK_business_usr__adviser_usr
        foreign key (user_details_id) references adviser_usr;

alter table car_model
    add constraint FK9_car_model__car_brand
        foreign key (car_brand_id) references car_brand;

alter table car_model
    add constraint FK_car_model__type_car
        foreign key (type_car_id) references type_car;

alter table image
    add constraint FK_image__user_car
        foreign key (user_car_id) references user_car;

alter table image
    add constraint FK_image__business
        foreign key (business_id) references business;

alter table point_with_business
    add constraint FK9_point_with_business__business
        foreign key (business_id) references business;

alter table point_with_business
    add constraint FK_point_with_business__history_point
        foreign key (history_point_id) references history_point;

alter table service
    add constraint FK_service__service_type
        foreign key (service_type_id) references service_type;

alter table service_type
    add constraint FK_service_type__business_type
        foreign key (business_type_id) references business_type;

alter table simple_usr
    add constraint FK_simple_usr__adviser_usr
        foreign key (user_details_id) references adviser_usr;

alter table user_car
    add constraint FK_user_car__car_model
        foreign key (car_model_id) references car_model;

alter table user_car
    add constraint FK_user_car__simple_usr
        foreign key (simple_user_user_details_id) references simple_usr;

alter table work_time
    add constraint FK_work_time__business
        foreign key (business_id) references business;