spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: xxxxxxx@gmail.com
    password: xxxxxxxxxxxxx
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
      connectiontimeout: 5000
      timeout: 3000
      writetimeout: 5000